### PR TITLE
Integer Literal + Minor Fixes

### LINKED ISSUE #27: Integer literal

### PR DESCRIPTION
**Pull request by Opeyem1a**
+ rename expected output to testSentence()
+ added integer literal
+ fix getByName()

Closes #27

### CODE REVIEW

File: src/temp/ClauseExample.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+        Example.main(new String[]{});
+    }
+
+    @RepeatedTest(50)
+    public void retrieveValueTest() {
+//        int randomIntegerValue = Integer.parseInt(getItemAtIndex(3));
+        if (getItemAtIndex(3) != null) {
+            int randomIntegerValue = Integer.parseInt(getItemAtIndex(3));
+            System.out.println(randomIntegerValue);
+            assertEquals(11, randomIntegerValue);
```
Comment (aadiraju) [inline src/temp/ClauseExample.java:30]: Wait what does this test do? Does it assert that the randomIntegerValue should be 11?  but won't it be a random integer from 0 to 9? So this test would fail always?

File: src/global/variables/IntegerLiteral.java [hunk 2]
```diff
@@ -0,0 +1,24 @@
+package global.variables;
+
+public class IntegerLiteral extends Clause {
```
Comment (aadiraju) [inline src/global/variables/IntegerLiteral.java:3]: Do you think it makes sense to have a float/double literal as well? Not sure if there is a use case, but I'm wondering if we'd need it

**Review by aadiraju — APPROVED** [review]
This looks good. Just some minor concerns I've outlined in the comments

File: src/temp/ClauseExample.java (hunk 1 above)
Comment (Opeyem1a) [reply src/temp/ClauseExample.java:30]: Yeah this is just test code so I wanted it to fail so I could see the value it retrieved

Comment (aadiraju) [reply src/temp/ClauseExample.java:30]: Okay perfect

File: src/global/variables/IntegerLiteral.java (hunk 2 above)
Comment (Opeyem1a) [reply src/global/variables/IntegerLiteral.java:3]: We were planning to add them already, I just wanted to get that ball rolling
